# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_comment_like_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.PostModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.UserModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment_like_model',
            name='Comment_text',
        ),
        migrations.RemoveField(
            model_name='comment_like_model',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment_Like_Model',
        ),
    ]
