# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0013_auto_20170730_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel1',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
