# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0014_auto_20170730_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel1',
            new_name='UserModel',
        ),
    ]
